version: 0.2

env:
  variables:
    region: "ap-southeast-2"
    bucket: "fromeroad"
    key: "prod.tfstate"

phases:
  install:
    commands:
      - cd /usr/bin
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/1.5.1/terraform_1.5.1_linux_amd64.zip
      - unzip -o terraform.zip
      - terraform --version
      - cd $CODEBUILD_SRC_DIR
      - echo $DOCKER_USER
      - docker login --username $DOCKER_USER --password $DOCKER_PWD
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $AWS_ID.dkr.ecr.$region.amazonaws.com
      - cd terraform && terraform init -var="ACCESS_KEY=$ACCESS_KEY" -var="SECRET_KEY=$SECRET_KEY" -backend-config="bucket=$bucket" -backend-config="region=$region" -backend-config="key=$key" -migrate-state
      - terraform plan -var="ACCESS_KEY=$ACCESS_KEY" -var="SECRET_KEY=$SECRET_KEY" -var="region=$region" -var="env=$ENV" -var="RDS_USER=$RDS_USER" -var="RDS_PASSWORD=$RDS_PWD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ../api && docker build -t fr_ecr_$ENV .
      - docker tag fr_ecr_$ENV:latest $AWS_ID.dkr.ecr.$region.amazonaws.com/fr_ecr_$ENV:latest
      - docker tag fr_ecr_$ENV $AWS_ID.dkr.ecr.$region.amazonaws.com/fr_ecr_$ENV:$CODEBUILD_BUILD_NUMBER
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ID.dkr.ecr.$region.amazonaws.com/fr_ecr_$ENV:latest
      - docker push $AWS_ID.dkr.ecr.$region.amazonaws.com/fr_ecr_$ENV:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - cd ../terraform
      - terraform apply -auto-approve -var="ACCESS_KEY=$ACCESS_KEY" -var="SECRET_KEY=$SECRET_KEY" -var="region=$region" -var="env=$ENV" -var="RDS_USER=$RDS_USER" -var="RDS_PASSWORD=$RDS_PWD"
