version: '3.3'
services:
  mysql_db:
    container_name: ${env}_fromeroad_mysql
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'fromeroad'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'fromeroadadmin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Sp3ndin*minEcraft+gBo0ted2-WisTfuL8'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Sp3ndin*minEcraft+gBo0ted2-WisTfuL8'
    networks:
      - docker_default
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${port}
    expose:
      # Opens port 3306 on the container
      - ${exposed_port}
      # Where our data will be persisted
    volumes:
      - ./${env}_db_data:/var/lib/mysql
  nodejs_api:
    container_name: ${env}_fromeroad_api
    image: fromeroadapi
    restart: always
    build:
      context: api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${env}
    depends_on:
      - mysql_db
    networks:
      - docker_default
    volumes:
      - ./${env}_api_data:/usr/src/app/data
# Names our volume

volumes:
  dev_api_data:
  dev_db_data:
  prod_api_data:
  prod_db_data:

   
networks:
  docker_default:
    external: true