const PRIVATE_KEY = `-----BEGIN RSA PRIVATE KEY-----\n
MIIBOgIBAAJBAIv1Bs3h1mP6qqtTdfqVHIvOuGROeIGhNjDzA0BA2K4aICRuiXA2\n
TnP8QnLUBW1sBVWrioRgMkqPlK2DHvKmCNMCAwEAAQJAd8y7kEv6GgadRJ3iZSZy\n
EvJWP/YzjLKUEn5RkBRx5URPPTraAkmQ2KUtV1FGZgvEXCDNzK3qx5T3XTREJUmI\n
MQIhAMcHl/eVa01yChf40IncPGvJ7FIfyefDFldVlacfUSZXAiEAtAS+JlEGS8+C\n
vGByRnX8sCwCfrDHlCrM5HANOTU/C+UCIAg5VBoy3mAw2iHrchKAOy7pBQ7PqXQe\n
J4osSybAsIW5AiAl1bFZQEJAgLaLfQHHiVi4did4FRN9MpmpkVtWILjFeQIhAIj9\n
pCKIJpZE1FRqXFXDMrmF9TvznI59DsC/jhsQz52j\n
-----END RSA PRIVATE KEY-----`

  
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----\n
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIv1Bs3h1mP6qqtTdfqVHIvOuGROeIGh\n
NjDzA0BA2K4aICRuiXA2TnP8QnLUBW1sBVWrioRgMkqPlK2DHvKmCNMCAwEAAQ==\n
----- END PUBLIC KEY-----`

exports.PUBLIC_KEY = PUBLIC_KEY;
exports.PRIVATE_KEY = PRIVATE_KEY;